### ISSUE TITLE
[nx] autocomplete doesn't work properly anymore

### ISSUE THREAD

**Issue by overbit** [withfig/autocomplete#1928]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

nx

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

Since https://github.com/withfig/autocomplete/pull/1915 the `nx` autocomplete doesn't prompt commands shown in the documentation anymore  (https://fig.io/manual/nx).

The most annoying miss is, of course the `nx serve`.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/2861984/233575051-f4f1aa73-5d4b-4929-9a58-95fa54098db0.png">

**Comment by fedeci** [comment]
I'm looking into this.

**Comment by fedeci** [comment]
@overbit what version of nx are you using?

**Comment by overbit** [comment]
15.4.5

```js
    "@nrwl/cypress": "15.4.5",
    "@nrwl/devkit": "^15.4.5",
    "@nrwl/eslint-plugin-nx": "15.4.5",
    "@nrwl/express": "15.4.5",
    "@nrwl/jest": "15.4.5",
    "@nrwl/js": "15.4.5",
    "@nrwl/linter": "15.4.5",
    "@nrwl/nest": "15.4.5",
    "@nrwl/node": "15.4.5",
    "@nrwl/nx-cloud": "15.0.3",
    "@nrwl/react": "15.4.5",
    "@nrwl/storybook": "15.4.5",
    "@nrwl/web": "15.4.5",
    "@nrwl/webpack": "15.4.5",
    "@nrwl/workspace": "15.4.5",
```
You said you reverted it but I can I get the latest version? `fig update ` returns that I'm running the latest.

**Comment by ikosta** [comment]
Sorry to drop in but the CLI documentation of NX is here: https://nx.dev/reference/commands#nx-cli-commands

The https://fig.io/manual/nx is some internal fig documentation that have not been updated.

Can you say what commands are missing? Because I removed all deprecated ones and wonder if I messed something up.

**Comment by ikosta** [comment]
@fedeci it would be great if we had a chat before this was reverted. Because right now there are a few guys that are wonder why the autocomplete for nx is again so poor.

**Comment by ikosta** [comment]
Just saw... the `nx serve`you are missing is implemented with the run-derived-subcommands: (https://github.com/withfig/autocomplete/blob/3b85e1a9d7678e9fb381a40e110c825390a0ce8e/src/nx.ts#L689)

For this you must know how the `nx run` command works and what that run-derived-subcommands are.

Every time you are using `nx serve something` the nx cli is executing `nx run something:serve:configuration`.

The only thing I noticed is that you are executing the nx command with `npx nx` but this should also work to give you a list with all projects.

**Comment by ikosta** [comment]
@fedeci sorry to speak out this way but the screenshot has exactly zero value, because it is alphabetical and you can scroll into it what you can't see here... also I am sure that if @overbit did put in `npx nx s` that the serve command would have been there. So I completely can not understand the decision of reverting.

**Comment by fedeci** [comment]
@ikosta `nx serve` isn't shown as a suggestion. Reverting is used to restore the project to a previous state that the maintainers are sure is working. Since we had the previous version for months I prefer to revert new features than break existing ones.

**Comment by ikosta** [comment]
@fedeci tge serve command is only visible when there is at least one project that has this target. Basically every app has this command. If you type nx outside a nx-repo there will be no serve because there is no project.json to check and fill up the projects, targets and configurations.

**Comment by fedeci** [comment]
@ikosta Got it, I was testing it like that. However in my repro I do not have `apps` or `libs` but I do have `packages` and  `preProcessProjects` is not working correctly.

**Comment by ikosta** [comment]
@fedeci can you provide me a repo to check that

**Comment by fedeci** [comment]
I am correcting it and pushing to main, I am adding you as co-author for the PR @ikosta, so that you get credit for the commits.

**Comment by fedeci** [comment]
`npx create-nx-workspace@latest myorg --preset=ts`

**Comment by ikosta** [comment]
> I am correcting it and pushing to main, I am adding you as co-author for the PR @ikosta, so that you get credit for the commits.

I don't care about getting credit. Just want to have it next level autocomplete 😝

**Comment by ikosta** [comment]
> > @fedeci can you provide me a repo to check that
> 
> `npx create-nx-workspace@latest myorg --preset=ts` does the work

ok... that's a new release with nx 16... let ne check what happens there

**Comment by fedeci** [comment]
`libs` and `apps` dirs are stored in the `nx.json` so we can retrieve them easily.

**Comment by ikosta** [comment]
for nx@16 yes... but nx@15 does not have this entries

**Comment by fedeci** [comment]
https://github.com/withfig/autocomplete/pull/1930/commits/7d025b35f48cc07fc5eded9f82c673a9fed92818#diff-83d1c6cef9dc94f9a457149936c4e9c181d469a70dc00263c101121da800700dR129-R140

**Comment by ikosta** [comment]
> [7d025b3#diff-83d1c6cef9dc94f9a457149936c4e9c181d469a70dc00263c101121da800700dR129-R140](https://github.com/withfig/autocomplete/commit/7d025b35f48cc07fc5eded9f82c673a9fed92818#diff-83d1c6cef9dc94f9a457149936c4e9c181d469a70dc00263c101121da800700dR129-R140)
> 
> We fallback to `apps` and `libs` for previous versions. I can assume @overbit was wrong, but we still got a future issue.

Yes... since nx@16. Thanks for fixing that. maybe we should abort the find for project.json's if there is no `nx.json` in the execution directory... this would fix an issue when having plenty nx-repos and execute the nx-autocomplete on the ../ directory... would load all project.json's from all repos right now.

**Comment by ikosta** [comment]
I will fix that next week and open a PR... thanks @fedeci

**Comment by fedeci** [comment]
@ikosta is it doing that rn? When `nx.json` is missing `cat nx.json` is non-zero and `executeShellCommand` rejects so the directory lookup should occurr.

**Comment by ikosta** [comment]
Yeah... you fixed that by accident 😉

**Comment by ikosta** [comment]
`npx nx affected:apps` & `npx nx affected:libs` -> deprecated -> not implemented in the new version. use `npx nx print-affected` instead

The repo you provided is in nx@15.4 and has a `workspace.json` and also`project.json`'s in the `libs` and `packages` directories. Since the `workspace.json` is not needed this is a misconfiguration on your end. Also the base directories are `libs` and `apps` and there is a property `workspaceLayout` in the `nx.json` where you can change that.

Overall you use deprecated commands and the repo has a misconfiguration.

**Comment by ikosta** [comment]
@overbit https://nx.dev/reference/nx-json#workspace-layout

**Comment by ikosta** [comment]
ok... you have that configured

**Comment by ikosta** [comment]
let me check where the error is

**Comment by ikosta** [comment]
@overbit you can maybe hot fix that till the PR is released by adding the misspelled `appDir` in the `workspaceLayout`.

**Comment by overbit** [comment]
Nice finding!
