### ISSUE TITLE
Suggestions don't appear (variadic)

### ISSUE THREAD

**Issue by ankithm28** [withfig/autocomplete#324]
**Summary:**
Suggestions that are variadic and are for options do not show up. 

Examples include: 

1. [https://github.com/withfig/autocomplete/blob/ae535b26f5340f5ec7352e89277f8585dae811c1/dev/git.ts#L681-L723](`git config --global`)
1. https://github.com/Monkeyank/autocomplete/blob/b1b5e38fd332a2442668b7be8a53e9b408636bb0/dev/stripe.ts#L594-L604

**Steps to Reproduce:**

1. `git config --global`
You can also look for other instances in the repo which have options that take arguments that are variadic.

**Expected Results:**
Suggestions should show up.

**Actual Results:**
Suggestions that are variadic and are for options do not show up. 

**System information:**
OS: MacOS Big Sur 11.0.1
Terminal: MacOS Terminal
Version of Fig: 1.0.43

**Additional Notes:**

**Comment by fwesss** [comment]
I wrote the eslint --env option so that it has the behavior I think you're looking for.
https://github.com/fwesss/autocomplete/blob/master/dev/eslint.ts#L17-L73

Pull request hasn't been merged yet, but it filters the suggestions by ',' and the previous options that have already been entered.

Since this seems to be a common way to spec options, maybe the variadic flag for options can be changed to mirror this behavior.

**Comment by Monkeyank** [comment]
> I wrote the eslint --env option so that it has the behavior I think you're looking for.
> 
> https://github.com/fwesss/autocomplete/blob/master/dev/eslint.ts#L17-L73
> 
> 
> 
> Pull request hasn't been merged yet, but it filters the suggestions by ',' and the previous options that have already been entered.
> 
> 
> 
> Since this seems to be a common way to spec options, maybe the variadic flag for options can be changed to mirror this behavior.

Definitely a good idea, but personally I like to just leave spaces between variadic arguments. 

Also, the main purpose of filing this issue is to make sure that in the future that the engine handles this, so users can do either!
