### ISSUE TITLE
[npx] Add support for npx completion spec

### ISSUE THREAD

**Issue by brendanfalk** [withfig/autocomplete#348]
Create a completion spec for npx, specifically for local packages

**Comment by QuiiBz** [comment]
@brendanfalk could you clarify what "specifically for local packages" means? The current `npx` spec have completion for cli such as prisma, react-native, etc. Those suggestions are always shown since you don't need to have those packages installed in your cwd to run them.

Would you mean that packages for cli installed in the current cwd should have a higher priority?

**Comment by QuiiBz** [comment]
Merged in #359!
