### ISSUE TITLE
[brew] incomplete spec

### ISSUE THREAD

**Issue by d7an** [withfig/autocomplete#647]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

brew

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

brew command will accept formula|cask without needing to specify a type. e.g. following command are both accepted.
brew info micro
or
brew info --cask micro

However, Fig's does not autocomplete cask unless you also specify --cask option.

**Comment by QuiiBz** [comment]
Looks like the issue is due to homebrew (I've run the script command executed in the spec's generator, with a grep to `handbrake `), as you can see there are two instances of `handbrake`. I'm going to fix this asap

![Screenshot 2021-10-14 at 18 15 06](https://user-images.githubusercontent.com/43268759/137356605-1908a258-b127-42d3-9d6f-a88a91904d45.png)
