### ISSUE TITLE
[man] Man command suggests only section 1 commands

### ISSUE THREAD

**Issue by ardeora** [withfig/autocomplete#663]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [X] I would like to work on this.

### What CLI tool does this relate to?

man

### Which statement makes the most sense?

This completion spec isn't complete

### Issue Details

I came across this issue when I was writing the completion spec for the `chown` command and saw that the `man` command doesn't offer suggestions for the `chown` command. This is because the `chown` man page resides in section 8 of the man path directories. Here is a handy list of what each section contains: 

|  Section | Description  |
|---|---|
| 1  | General commands  |
|  2 | System calls  |
|  3 |  Library functions, covering in particular the C standard library |
|  4 |  Special files (usually devices, those found in /dev) and drivers |
|  5 | File formats and conventions  |
|  6 |  Games and screensavers |
|  7 | Miscellaneous  |
|  8 |  System administration commands and daemons |

Right now the suggestion generator only looks for man page section `1`. I believe we should also include section `8` at least. Would love to hear your thoughts. If you decide to go ahead with it. I would love to make that change 😄 

Here is the line with the potential issue: https://github.com/ardeora/autocomplete/blob/master/src/man.ts#L8

**Comment by SeparateRecords** [comment]
@ardeora Are you still interested in adding this? If not I'd be happy to have a go.

I think showing section 1 without specifying a section is reasonable, most people don't need to care about syscall documentation. Pages from other sections could be suggestions after specifying a section, and sections could be suggested with the highest priority (with their human readable name instead of a just number)

For reference for later:

Section | Title
--- | ---
1 | General commands
2 | System calls
3 | Library functions, covering in particular the C standard library
4 | Special files (usually devices, those found in /dev) and drivers
5 | File formats and conventions
6 | Games and screensavers
7 | Miscellaneous
8 | System administration commands and daemons
