### ISSUE TITLE
[awscli] s3 ls issue

### ISSUE THREAD

**Issue by Ezzahhh** [withfig/autocomplete#700]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

awscli

### Which statement makes the most sense?

There is a bug with this completion spec

### Issue Details

When using the command `aws s3 ls` and pressing enter to execute the command, the command is not actually executed. The cursor will go down into a new line but not execute. If I press the enter key again then the command will be executed. I believe this to be a bug specific to the spec because the issue does not occur when Fig is disabled for the Terminal.

**Comment by brendanfalk** [comment]
Thanks for this. Could you upload a video of what's going on? 

My assumption is this is because we flag `aws s3 ls` as taking a mandatory arg. Therefore I think we are automatically inserting a space as opposed to executing the command. I don't use aws much. Is it possible to run `aws s3 ls` on its own without any arguments? 

If so, this can be fixed in the s3 completion spec (https://github.com/withfig/autocomplete/blob/master/src/aws/s3.ts) by adding isOptional to the arg object here (https://github.com/withfig/autocomplete/blob/master/src/aws/s3.ts#L410)

Let's see the video first!

**Comment by Ezzahhh** [comment]
Here is a gif showing the issue: https://cln.sh/zJqMNg
I just did a local test with the `isOptional` option and it appears to resolve the problem! Might be worth opening a PR for the completion spec sometime; I think there were a few other commands that were missing the `isOptional` flag, but I'll need to find them again.
